#!/bin/zsh

if [ -z "$ZSHDIR" ]; then
    ZSHDIR="$(dirname "$(readlink -f "$0")")"
fi

(! (($path[(Ie)$HOME/.yarn/bin])) ) && path=( "$HOME/.yarn/bin" $path )
(! (($path[(Ie)$HOME/.cargo/bin])) ) && path=( "$HOME/.cargo/bin" $path )
(! (($path[(Ie)$HOME/.local/bin])) ) && path=( "$HOME/.local/bin" $path )
(! (($path[(Ie)$ZSHDIR/pyenv/bin])) ) && path=( "$ZSHDIR/pyenv/bin" $path )
(! (($path[(Ie)$ZSHDIR/bin])) ) && path=( "$ZSHDIR/bin" $path )
(! (($path[(Ie)$ZSHDIR/pyenv/shims])) ) && path=( "$ZSHDIR/pyenv/shims" $path )
export PATH

export FNVM_NVMDIR="$ZSHDIR/nvm"
export FNVM_DIR="$ZSHDIR/fnvm"
export NVM_DIR="$ZSHDIR/nvm"
export PYENV_ROOT="$ZSHDIR/pyenv"
export CARGO_HOME="$HOME/.cargo"
export RUSTUP_HOME="$ZSHDIR/rustup"

source $ZSHDIR/fnvm/fnvm.sh; FNVM_DISABLE_CD=yes fnvm_init
source $ZSHDIR/lib.zsh

if [ ! -z "$CWD" ]; then
	cd "$CWD"
fi

if [[ "$NOEXEC" == "1" ]]; then
	"$@"
	exit "$?"
else
	exec "$@"
fi

